version: '3'

networks:
    dbwebb:

services:
    server:
        image: richpotato/backend:latest
        container_name: 'backend'
        ports:
          - "8000:8000"
        networks:
            dbwebb:
        restart:
            "always"
    bikeprogram:
        image: richpotato/bikeprogram:latest
        container_name: 'bikeprogram'
        networks:
            dbwebb:
        links:
            - server:backend
    frontend:
        image: richpotato/frontend:latest
        container_name: "frontend"
        ports:
            - "1339:1339"
        networks:
            dbwebb:
        # ska den länkas?
        links:
            - server:backend
        restart:
            "always"

#docker-compose up -d server
#docker-compose up -d frontend
#docker-compose run bikeprogram
#docker-compose stop server
#docker-compose stop frontend
